import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Header from "../components/Header";
import Script from "next/script";
import Footer from "../components/Footer";
import AdSense from "@/adSense/adSense";
// import { GlobalContextProvider } from "./context/store";

// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Script src="./libs/jquery/dist/jquery.min.js"></Script>

      <Script src="./libs/popper.js/dist/umd/popper.min.js"></Script>
      <Script src="./libs/bootstrap/dist/js/bootstrap.min.js"></Script>

      <Script src="./libs/pjax/pjax.min.js"></Script>
      <Script src="./assets/js/ajax.js"></Script>

      <Script src="./assets/js/lazyload.config.js"></Script>
      <Script src="./assets/js/lazyload.js"></Script>
      <Script src="./assets/js/plugin.js"></Script>

      <Script src="./libs/scrollreveal/dist/scrollreveal.min.js"></Script>
      <Script src="./libs/slick-carousel/slick/slick.min.js"></Script> 

      <Script src="./libs/feather-icons/dist/feather.min.js"></Script> 

       <Script src="./assets/js/theme.js"></Script>   */}

      <head>
        <AdSense pId="5942356139252622" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} layout-column bg-dark`}
      >
        {/* <GlobalContextProvider> */}
        <Header />
        {children}
        <Footer />
        {/* </GlobalContextProvider> */}
      </body>
    </html>
  );
}
